theme: jekyll-theme-minimal
title: "Mulesoft Tutorial for beginner"
description: "A This is a short and brief tutorial for mulesoft"
url                      : "https:www.jansengoyena.xyz"
baseurl                  : "/blogs"
repository               : "jansen07/blogs"
