theme: jekyll-theme-minimal
title: "Mulesoft Tutorial for beginner"
description: "A This is a short and brief tutorial for mulesoft"
url                      : "https:ww.jansengoyena.xyz"
baseurl                  : "/jekyll"
repository               : "jansen07/jekyll"
